#define SAMPLE_ID_VOICE_4BIT 0
#define SAMPLE_ID_VOICE_2BIT 1
#define SAMPLE_ID_VOICE_1BIT 2
#define SAMPLE_ID_DCBIASEND_4BIT 3
#define SAMPLE_ID_DCBIASEND_2BIT 4
#define SAMPLE_ID_DCBIASEND_1BIT 5
#define SAMPLE_ID_BUGLOOP_2BIT 6
#define SAMPLE_ID_LONG_1BIT 7
